- action: set_fact default_policy=ACCEPT
  when: 'default_accept is defined and default_accept.lower() in ["1", "true"]'
  tags: iptables

- action: set_fact default_policy=DROP
  when: default_policy is not defined
  tags: iptables

- action: template dest=/etc/sysconfig/iptables src=iptables.rules.j2 owner=root group=root mode=0644
  notify: restart iptables
  tags: iptables