- name: configure munge
  action: copy src=etc/munge/munge.key dest=/etc/munge/munge.key owner=munge group=munge mode=0400
  tags: slurm

- name: start munge
  action: service name=munge state=started enabled=yes
  tags: slurm

- name: configure slurm
  action: template src=slurm.conf.j2 dest=/etc/slurm/slurm.conf owner=root group=root mode=0644
  tags: slurm

- name: ensure directory slurm for log exists
  action: file path=/var/log/slurm state=directory
  tags: slurm

- name: start slurm
  action: service name=slurm state=started enabled=yes
  tags: slurm

- name: configure hosts
  action: template src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
  tags: slurm
